### PR TITLE
Number abbreviations zhCN exceptions

### PR DESCRIPTION
**Pull request by Mengqyzh**
## Proposed changes
-------------------
Number abbreviations zhCN exceptions
tooltips-blizzard.lua -- Unadjusted structure

## Types of changes
-------------------
What types of changes does your code introduce?
_Put an `x` in the boxes that apply_

- [x] Localization (translation to a missing client locale, or updates to a previous non-English one)
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Make sure you can check the following boxes
----------------------------------------------

- [x] I've tried to the best of my ability to follow the same coding and formatting style as the main dev. 
- [x] I realize the code falls under the MIT license of the project and isn't technically mine anymore. 
- [x] I am aware that this might be rejected if it's not in line with the project's vision in any shape or form.

### CODE REVIEW

**Comment by goldpaw** [comment]
This one was a little hard to fit in. 

But since the same functions are being repeated in so many files, I moved these into a single library in the back-end folder instead, and now let all other libraries, plugins and modules get their functions from this. 

I included your fixes in this.

**Comment by Mengqyzh** [comment]
Nice to see you make changes, but zhCN exceptions you seem to have missed tooltips-blizzard

**Comment by goldpaw** [comment]
Fixed!

**Comment by Mengqyzh** [comment]
Thanks for your work,No error reported after testing

**Pull request closed without merging**
